ListProjects:
    resource: ../../src/ListProjects/Infrastructure/ListProjectsController.php
    type: annotation

RegisterProject:
    resource: ../../src/RegisterProject/Infrastructure/RegisterProjectController.php
    type: annotation

RegisterMigrations:
    resource: ../../src/RegisterMigrations/Infrastructure/RegisterMigrationsController.php
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
