services:
    _defaults:
      autowire: true
      autoconfigure: true

    App\ListProjects\:
       resource: '%kernel.project_dir%/src/ListProjects/'

    App\ListProjects\Test\Application\ListProjectsHandler\ListProjectsHandlerTestAssertions:
       public: true

    App\ListProjects\Test\Application\ListProjectsHandler\ListProjectsHandlerTestData:
       public: true
